// <auto-generated />
using System;
using AssessoriaCartoesApi.Data.DbContextAssessoria;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssessoriaCartoesApi.Data.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20211230020146_addcolumnclientetipousuario")]
    partial class addcolumnclientetipousuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Conciliador")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("ExtensaoLogo")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Img")
                        .HasColumnType("longblob");

                    b.Property<string>("NomeArquivoLogo")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PowerBi")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoDeUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.EASSESSORIA.AjusteEASSESSORIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgenciaDeDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAjusteNexxera")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeCompensacaoDoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoProduto")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoOriginalDeAjusteNexxera")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaDeDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVendaAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeReferencia")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoLancamentoDoAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDeAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDoMotivoDoAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("IdDaOcorrencia")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDeReferencia")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoProcesso")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoAtual")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoOriginal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAjustado")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVOriginal")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDoLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcelaAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTaxaDeServico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AjusteEASSESSORIA");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.EASSESSORIA.AntecipacaoEASSESSORIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgenciaDeDepositoDoCredito")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeCompensacaoDoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaDeDepositoDoCredito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoVencimento")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoOriginalDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoAntecipacaoDeRecebiveis")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoOriginalDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorInicialNegociadoParaAAntecipacao")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoCreditado")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoOriginalDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AntecipacaoEASSESSORIA");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.EASSESSORIA.FinanceiraSemVendaEASSESSORIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcelaResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaAntecipacaoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorPagoParcelaResumo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FinanceiraSemVendaEASSESSORIA");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.EASSESSORIA.FinanceiroEASSESSORIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("AgenciaLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrenteLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDaConciliacaoManualBancaria")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraTransacao")
                        .HasColumnType("longtext");

                    b.Property<string>("IndentificacaoDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTerminal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("OrdemDaInformacao")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDaConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDePagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxaDeDesconto")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalBrutoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalDoDescontoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalLiquidoDaVenda")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FinanceiroEASSESSORIA");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.EASSESSORIA.TransacaoEASSESSORIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("AgenciaLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrenteLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDaConciliacaoManualBancaria")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraTransacao")
                        .HasColumnType("longtext");

                    b.Property<string>("IndentificacaoDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTerminal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("OrdemDaInformacao")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDaConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDePagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxaDeDesconto")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalBrutoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalDoDescontoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalLiquidoDaVenda")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransacaoEASSESSORIA");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.EASSESSORIA.VendaEASSESSORIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("AgenciaLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrenteLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDaConciliacaoManualBancaria")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraTransacao")
                        .HasColumnType("longtext");

                    b.Property<string>("IndentificacaoDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTerminal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("OrdemDaInformacao")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDaConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDePagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxaDeDesconto")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalBrutoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalDoDescontoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalLiquidoDaVenda")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VendaEASSESSORIA");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.ExecucaoIntegracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataExecucaoFinalizada")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ExecucaoIntegracoes");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.G5SMART.AjusteG5SMART", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgenciaDeDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAjusteNexxera")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeCompensacaoDoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoProduto")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoOriginalDeAjusteNexxera")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaDeDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVendaAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeReferencia")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoLancamentoDoAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDeAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDoMotivoDoAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("IdDaOcorrencia")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDeReferencia")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoProcesso")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoAtual")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoOriginal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAjustado")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVOriginal")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDoLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcelaAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoAjuste")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTaxaDeServico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AjusteG5SMART");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.G5SMART.AntecipacaoG5SMART", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgenciaDeDepositoDoCredito")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeCompensacaoDoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaDeDepositoDoCredito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoVencimento")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoOriginalDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoAntecipacaoDeRecebiveis")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoOriginalDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorInicialNegociadoParaAAntecipacao")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoCreditado")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoOriginalDaParcelaDeResumo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AntecipacaoG5SMART");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.G5SMART.FinanceiraSemVendaG5SMART", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcelaResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaAntecipacaoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorPagoParcelaResumo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FinanceiraSemVendaG5SMART");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.G5SMART.FinanceiroG5SMART", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("AgenciaLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrenteLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDaConciliacaoManualBancaria")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraTransacao")
                        .HasColumnType("longtext");

                    b.Property<string>("IndentificacaoDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTerminal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("OrdemDaInformacao")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDaConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDePagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxaDeDesconto")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalBrutoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalDoDescontoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalLiquidoDaVenda")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FinanceiroG5SMART");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.G5SMART.TransacaoG5SMART", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("AgenciaLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrenteLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDaConciliacaoManualBancaria")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraTransacao")
                        .HasColumnType("longtext");

                    b.Property<string>("IndentificacaoDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTerminal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("OrdemDaInformacao")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDaConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDePagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxaDeDesconto")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalBrutoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalDoDescontoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalLiquidoDaVenda")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransacaoG5SMART");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.G5SMART.VendaG5SMART", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("AgenciaLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("BPAGID")
                        .HasColumnType("longtext");

                    b.Property<string>("BandeiraDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJDoEstabelecimento")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAgrupadorBancarioDoComprovante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDaBandeira")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDeAutorizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoDoBancoLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrente")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaCorrenteLiquidada")
                        .HasColumnType("longtext");

                    b.Property<string>("ControleERP")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDeEnvioAoBanco")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoCreditoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoDeposito")
                        .HasColumnType("longtext");

                    b.Property<string>("DataDoResumoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoDaConciliacaoManualBancaria")
                        .HasColumnType("longtext");

                    b.Property<string>("HashId")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraTransacao")
                        .HasColumnType("longtext");

                    b.Property<string>("IndentificacaoDeConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUCV")
                        .HasColumnType("longtext");

                    b.Property<string>("NSUTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeDaAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaNotaFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoCartao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroDoResumoRV")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTerminal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroTotalDeParcelas")
                        .HasColumnType("longtext");

                    b.Property<string>("OrdemDaInformacao")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVAdquirente")
                        .HasColumnType("longtext");

                    b.Property<string>("PDVTEF")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDaConciliacao")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusDePagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxaDeDesconto")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeCaptura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeRegistro")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDeVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorBrutoParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDescontoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorDoDescontoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoAntecipacaoParcelaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcela")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorLiquidoDaParcelaDeCreditoResumo")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalBrutoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalDoDescontoDaVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorTotalLiquidoDaVenda")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VendaG5SMART");
                });

            modelBuilder.Entity("AssessoriaCartoesApi.Data.Entities.LogNexxera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Exception")
                        .HasColumnType("longtext");

                    b.Property<string>("Filename")
                        .HasColumnType("longtext");

                    b.Property<string>("InnerException")
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeColunas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LogsNexxera");
                });
#pragma warning restore 612, 618
        }
    }
}
